spring.cloud.openfeign.client.config:
    default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
    fileService:
        url: ${FILE_SERVICE_URL:http://localhost:8290/object}
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        dismiss404: false
        micrometer.enabled: false