spring:
  application:
    name: open-feign-client
  cloud:
    openfeign:
      circuitbreaker.enabled: true
      client:
        config:
          default:
            connectTimeout: 1000
            readTimeout: 1000
            loggerLevel: full
            retryer: feign.NaiveRetryer
  security:
    oauth2:
      client:
        registration:
          wso2:
            client-name: Open Feign Client
            clientId: jtNHcXlSdLXnIVvbPg6UD3CJyW8a
            clientSecret: p9ZbVk3b1bWyzwA1Nbz_czZG_1wa
            authorization-grant-type: client_credentials
        provider:
          wso2:
            token-uri: https://is.cdc.zone:30300/oauth2/token
            authorization-uri: https://is.cdc.zone:30300/oauth2/authorize
custom.native-retryer:
  maxAttempts: 3
  period: 1000
  maxPeriod: 10000
feign:
  circuitbreaker:
    enabled: true
    alphanumeric-ids:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      WeatherFeigncurrentStringString:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
#        maxWaitDurationInHalfOpenState: 1
        waitDurationInOpenState: 60000
        registerHealthIndicator: true
  timelimiter:
    instances:
      WeatherFeigncurrentStringString:
        timeoutDuration: 60s
        registerHealthIndicator: true
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: "ALWAYS"
  health:
    circuitbreakers.enabled: true
    ratelimiters.enabled: true