spring:
    cloud:
        openfeign:
            circuitbreaker.enabled: true
            client:
                config:
                    default:
                        connectTimeout: 5000
                        readTimeout: 5000
                        loggerLevel: basic
                        retryer: feign.Retryer.Default
feign:
  circuitbreaker:
    enabled: true
    alphanumeric-ids:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      WeatherFeigncurrentStringString:
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
  timelimiter:
    instances:
      WeatherFeigncurrentStringString:
        timeoutDuration: 10s
